use super::geometry::{map_31, scale, Color};

const HOURGLASS_LEVELS: [u8; 13] = [0, 10, 20, 30, 55, 80, 105, 130, 155, 180, 205, 230, 255];
const HOURGLASS: &str = concat!(
    "MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM",
    "MMAAAAAAAAAAAAAAAAAAAAAAAAAAAMM",
    "MMMAAAAAAAAAAAAAAAAAAAAAAAAAMMM",
    "MMMMAAAAAAAAAAAAAAAAAAAAAAAMMMM",
    "MMMMMAAAAAAAAAAAAAAAAAAAAAMMMMM",
    "MMMMMMAAAAAAAAAAAAAAAAAAAMMMMMM",
    "MMMMMMMAAAAAAAAAAAAAAAAAMMMMMMM",
    "MMMMMMMMAAAAAAAAAAAAAAAMMMMMMMM",
    "MMMMMMMMMAAAAAAAAAAAAAMMMMMMMMM",
    "MMMMMMMMMMAAAAAAAAAAAMMMMMMMMMM",
    "MMMMMMMMMMMAAAAAAAAAMMMMMMMMMMM",
    "MMMMMMMMMMMMAAAAAAAMMMMMMMMMMMM",
    "MMMMMMMMMMMMMAAAAAMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMAAAMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMAMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MAAAAAAAAAAAAAAMAAAAAAAAAAAAAAM",
    "MMAAAAAAAAAAAAAMAAAAAAAAAAAAAMM",
    "MMMAAAAAAAAAAAAMAAAAAAAAAAAAMMM",
    "MMMMAAAAAAAAAAAMAAAAAAAAAAAMMMM",
    "MMMMMAAAAAAAAAAMAAAAAAAAAAMMMMM",
    "MMMMMMAAAAAAAAAMAAAAAAAAAMMMMMM",
    "MMMMMMMAAAAAAAAMAAAAAAAAMMMMMMM",
    "MMMMMMMMAAAAAAAMAAAAAAAMMMMMMMM",
    "MMMMMMMMMAAAAAAMAAAAAAMMMMMMMMM",
    "MMMMMMMMMMAAAAAMAAAAAMMMMMMMMMM",
    "MMMMMMMMMMMAAAAMAAAAMMMMMMMMMMM",
    "MMMMMMMMMMMMAAAMAAAMMMMMMMMMMMM",
    "MMMMMMMMMMMMMAAMAAMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMAMAMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MAAAAAAAAAAAAAMMMAAAAAAAAAAAAAM",
    "MMAAAAAAAAAAAAMMMAAAAAAAAAAAAMM",
    "MMMAAAAAAAAAAAMMMAAAAAAAAAAAMMM",
    "MMMMAAAAAAAAAAMMMAAAAAAAAAAMMMM",
    "MMMMMAAAAAAAAAMMMAAAAAAAAAMMMMM",
    "MMMMMMAAAAAAAAMMMAAAAAAAAMMMMMM",
    "MMMMMMMAAAAAAAMMMAAAAAAAMMMMMMM",
    "MMMMMMMMAAAAAAMMMAAAAAAMMMMMMMM",
    "MMMMMMMMMAAAAAMMMAAAAAMMMMMMMMM",
    "MMMMMMMMMMAAAAMMMAAAAMMMMMMMMMM",
    "MMMMMMMMMMMAAAMMMAAAMMMMMMMMMMM",
    "MMMMMMMMMMMMAAMMMAAMMMMMMMMMMMM",
    "MMMMMMMMMMMMMAMMMAMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MAAAAAAAAAAAAMMMMMAAAAAAAAAAAAM",
    "MMAAAAAAAAAAAMMMMMAAAAAAAAAAAMM",
    "MMMAAAAAAAAAAMMMMMAAAAAAAAAAMMM",
    "MMMMAAAAAAAAAMMMMMAAAAAAAAAMMMM",
    "MMMMMAAAAAAAAMMMMMAAAAAAAAMMMMM",
    "MMMMMMAAAAAAAMMMMMAAAAAAAMMMMMM",
    "MMMMMMMAAAAAAMMMMMAAAAAAMMMMMMM",
    "MMMMMMMMAAAAAMMMMMAAAAAMMMMMMMM",
    "MMMMMMMMMAAAAMMMMMAAAAMMMMMMMMM",
    "MMMMMMMMMMAAAMMMMMAAAMMMMMMMMMM",
    "MMMMMMMMMMMAAMMMMMAAMMMMMMMMMMM",
    "MMMMMMMMMMMMAMMMMMAMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "AAAAAAAAAAAALLLLLLLAAAAAAAAAAAA",
    "AAAAAAAAAAAKKKKKKKKKAAAAAAAAAAA",
    "AAAAAAAAAAJJJJJJJJJJJAAAAAAAAAA",
    "AAAAAAAAAIIIIIIIIIIIIIAAAAAAAAA",
    "AAAAAAAAHHHHHHHHHHHHHHHAAAAAAAA",
    "AAAAAAAGGGGGGGGGGGGGGGGGAAAAAAA",
    "AAAAAAFFFFFFFFFFFFFFFFFFFAAAAAA",
    "AAAAAEEEEEEEEEEEEEEEEEEEEEAAAAA",
    "AAAADDDDDDDDDDDDDDDDDDDDDDDAAAA",
    "AAACCCCCCCCCCCCCCCCCCCCCCCCCAAA",
    "AABBBBBBBBBBBBBBBBBBBBBBBBBBBAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
);
const ELECTRIC: &str = concat!(
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
    "BBAAAAAAAAAAAAAAAAAAAAAAAAAAABB",
    "BBBAAAAAAAAAAAAAAAAAAAAAAAAABBB",
    "BBBBAAAAAAAAAAAAAAAAAAAAAAABBBB",
    "BBBBBAAAAAAAAAAAAAAAAAAAAABBBBB",
    "BBBBBBAAAAAAAAAAAAAAAAAAABBBBBB",
    "CBBBBBBAAAAAAAAAAAAAAAAABBBBBBC",
    "CCBBBBBBAAAAAAAAAAAAAAABBBBBBCC",
    "CCCBBBBBBAAAAAAAAAAAAABBBBBBCCC",
    "CCCCBBBBBBAAAAAAAAAAABBBBBBCCCC",
    "CCCCCBBBBBBAAAAAAAAABBBBBBCCCCC",
    "CCCCCCBBBBBBAAAAAAABBBBBBCCCCCC",
    "ACCCCCCBBBBBBAAAAABBBBBBCCCCCCA",
    "AACCCCCCBBBBBBAAABBBBBBCCCCCCAA",
    "AAACCCCCCBBBBBBABBBBBBCCCCCCAAA",
    "AAAACCCCCCBBBBBBBBBBBCCCCCCAAAA",
    "AAAAACCCCCCBBBBBBBBBCCCCCCAAAAA",
    "AAAAAACCCCCCBBBBBBBCCCCCCAAAAAA",
    "AAAAAAACCCCCCBBBBBCCCCCCAAAAAAA",
    "AAAAAAAACCCCCCBBBCCCCCCAAAAAAAA",
    "AAAAAAAAACCCCCCBCCCCCCAAAAAAAAA",
    "AAAAAAAAAACCCCCCCCCCCAAAAAAAAAA",
    "AAAAAAAAAAACCCCCCCCCAAAAAAAAAAA",
    "AAAAAAAAAAAACCCCCCCAAAAAAAAAAAA",
    "AAAAAAAAAAAAACCCCCAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAACCCAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAACAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAACCCAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAACCCCCAAAAAAAAAAAAA",
    "AAAAAAAAAAAACCCCCCCAAAAAAAAAAAA",
    "AAAAAAAAAAACCCCCCCCCAAAAAAAAAAA",
    "AAAAAAAAAACCCCCBCCCCCAAAAAAAAAA",
    "AAAAAAAAACCCCCBBBCCCCCAAAAAAAAA",
    "AAAAAAAACCCCCBBBBBCCCCCAAAAAAAA",
    "AAAAAAACCCCCBBBBBBBCCCCCAAAAAAA",
    "AAAAAACCCCCBBBBBBBBBCCCCCAAAAAA",
    "AAAAACCCCCBBBBBBBBBBBCCCCCAAAAA",
    "AAAACCCCCBBBBBBABBBBBBCCCCCAAAA",
    "AAACCCCCBBBBBBAAABBBBBBCCCCCAAA",
    "AACCCCCBBBBBBAAAAABBBBBBCCCCCAA",
    "ACCCCCBBBBBBAAAAAAABBBBBBCCCCCA",
    "CCCCCBBBBBBAAAAAAAAABBBBBBCCCCC",
    "CCCCBBBBBBAAAAAAAAAAABBBBBBCCCC",
    "CCCBBBBBBAAAAAAAAAAAAABBBBBBCCC",
    "CCBBBBBBAAAAAAAAAAAAAAABBBBBBCC",
    "CBBBBBBAAAAAAAAAAAAAAAAABBBBBBC",
    "BBBBBBAAAAAAAAAAAAAAAAAAABBBBBB",
    "BBBBBAAAAAAAAAAAAAAAAAAAAABBBBB",
    "BBBBAAAAAAAAAAAAAAAAAAAAAAABBBB",
    "BBBAAAAAAAAAAAAAAAAAAAAAAAAABBB",
    "BBAAAAAAAAAAAAAAAAAAAAAAAAAAABB",
    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
);

pub(super) fn hourglass(led_count: usize, colors: &[Color; 6], brightness: u8) -> Vec<Vec<Color>> {
    let table = HOURGLASS.as_bytes();
    let mut frames = Vec::with_capacity(280);
    for color in colors.iter().take(4) {
        for row in 0..70 {
            let path = std::array::from_fn(|column| {
                let level = HOURGLASS_LEVELS[(table[row * 31 + column] - b'A') as usize];
                scale(scale(*color, level), brightness)
            });
            frames.push(map_31(&path, led_count));
        }
    }
    frames
}

pub(super) fn electric_current(
    led_count: usize,
    colors: &[Color; 6],
    brightness: u8,
) -> Vec<Vec<Color>> {
    let table = ELECTRIC.as_bytes();
    let mut rows = Vec::with_capacity(45);
    rows.extend(std::iter::repeat_n(0, 5));
    rows.extend(1..=28);
    rows.extend((30..=52).step_by(2));
    let mut frames = Vec::with_capacity(180);
    for color in colors.iter().take(4) {
        for &row in &rows {
            let path = std::array::from_fn(|column| {
                let source = table[row * 31 + column] - b'A';
                let color = match source {
                    1 => *color,
                    2 => [255; 3],
                    _ => [0; 3],
                };
                scale(color, brightness)
            });
            frames.push(map_31(&path, led_count));
        }
    }
    frames
}
